# Generated by Django 2.2.4 on 2019-09-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField(max_length=20)),
                ('sender', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.TextField(max_length=20)),
                ('search_by', models.TextField(blank=True, choices=[('title', 'Search by title'), ('goodreads_id', 'Search by Goodreads id')], max_length=16, null=True)),
            ],
        ),
    ]
