# Generated by Django 2.2.4 on 2019-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.TextField(max_length=20)),
                ('search_by', models.TextField(blank=True, choices=[('title', 'title'), ('goodreads_id', 'goodsreads id')], max_length=16, null=True)),
            ],
        ),
    ]
